### ISSUE TITLE
Add flag to enforce subdirectory == subdirectory in index.json

### ISSUE THREAD

**Issue by dholth** [conda/conda-index#105]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

It can cause problems when a package is built for a subdirectory but is placed into a different subdirectory (e.g. a linux-64 package copied into noarch/)

Add a strict flag to either error or ignore those packages when index.json's subdir does not match. Then a mismatched package would not show up in repodata.json.

Remember that old packages might have a platform= in index.json or nothing at all? instead of subdir.

**Comment by kenodegard** [comment]
See recent incident on conda-forge: https://github.com/conda-forge/status/issues/144

**Comment by kenodegard** [comment]
I'm thinking this check should be enabled by default with the option to disable

**Comment by wolfv** [comment]
Sounds reasonable to me. I think it should also emit a warning (or maybe even error?).

**Comment by dholth** [comment]
Is it correct that within the last year libmamba promoted "subdir mismatch" as something to crash on, which was not previously the case?

**Comment by kenodegard** [comment]
Not libmamba, libsolv

**Comment by wolfv** [comment]
Yeah, libsolv added this check at some point. I didn't ever think that it would be possible to have mixed-arch packages in the subdirs though.

**Comment by dholth** [comment]
When developing `conda-index` it was really useful to use `~/miniconda3/pkgs/cache` as something to index (these are not split out by subdir). Maybe not a common case, I wonder if we could handle these intelligently by automatically splitting them into their proper subdirectories.
