### ISSUE TITLE
Prepare 0.3 release?

### ISSUE THREAD

**Issue by jaimergp** [conda/conda-index#116]
There are a couple of user-facing PRs that could use a release:

- https://github.com/conda/conda-index/pull/79
- https://github.com/conda/conda-index/pull/88
- https://github.com/conda/conda-index/pull/112
- https://github.com/conda/conda-index/pull/110

Are we waiting for something or can we start preparing the release?

**Comment by dholth** [comment]
Yes, we can start preparing the release 🏁

**Comment by jaimergp** [comment]
What's the release process like in this repo? I can help set it up, but I see no `rever.xsh` so I am assuming it's different than `conda/conda`.

**Comment by jaimergp** [comment]
Thanks!
