### ISSUE TITLE
Add fsspec support to index remote filesystems, separate package / cache, database / output directories into 3 places.

### ISSUE THREAD

**Issue by dholth** [conda/conda-index#143]
### What is the idea?

Allow an optional fsspec dependency to index remote packages through the API. When fsspec is not installed local packages can still be indexed as usual.

Separate input, cache (sqlite databases), and output into three directories. By default these can be the same folder, but with fsspec the input will typically be read-only and not usable for the sqlite cache database.

### Why is this needed?

This will be used to improve the CDN process.

**Comment by jtroe** [comment]
These changes look like they will help me; I'm currently working on creating an index in s3 and CloudFront.  Are there plans to add `channel_url` to the CLI?

**Comment by dholth** [comment]
That's great! It would be interesting to add `channel_url` to the CLI. One challenge is that it would not be completely general; for example if the remote filesystem is HTTP then conda_index might call HEAD on each individual remote file to get the equivalent of `mtime`; those details might need to be stored out-of-band by overriding [save_fs_state](https://github.com/conda/conda-index/blob/main/conda_index/index/sqlitecache.py#L439) or by relaxing the comparison in [changed_packages](https://github.com/conda/conda-index/blob/main/conda_index/index/sqlitecache.py#L439) to only consider metadata that we could efficiently gather from upstream. On the other hand a s3 list would be reasonably efficient for small or medium sized channels.
