### ISSUE TITLE
Graduate to main conda organization

### ISSUE THREAD

**Issue by dholth** [conda/conda-index#59]
As a follow-up to https://github.com/conda/conda-build/issues/4472 (**"Split `conda index` into separate package `conda-index`"**) we are ready to remove the `conda index` subcommand from conda-build and have conda-build instead depend on conda-index.

**In preparation for that we need to graduate `conda-index` to the main conda organization.**

`conda-build` would depend on `conda-index` -> `conda-package-streaming` -> `python-zstandard`.

I don't think conda-build usually spends a lot of time indexing, since you're not likely to have thousands of local packages, but this would make it faster.

This is also related to another graduation application: https://github.com/conda-incubator/conda-package-streaming/issues/31

**Comment by jezdez** [comment]
@conda-incubator/steering

This proposal falls under the **[Incorporate a Software Project into the main conda Organization](https://github.com/conda-incubator/governance/tree/eaf59a5779dc1f678bee4453ceb92fd733e7306a#incorporate-a-software-project-into-the-main-conda-organization)** policy of the [conda governance policy](https://github.com/conda-incubator/governance), please vote and/or comment on this proposal.

It **needs 60% of the Steering Council** to vote `yes` to pass.

To vote, please leave `yes`, `no` or `abstain` as comments below this issue.

If you have questions concerning the proposal, please leave a comment below as well.

**This vote will end on 2022-10-07.**

**Comment by beckermr** [comment]
yes

**Comment by jezdez** [comment]
yes

**Comment by marcelotrevisani** [comment]
Yes

**Comment by ocefpaf** [comment]
Yes

**Comment by wolfv** [comment]
yes, nice!

**Comment by jaimergp** [comment]
Yes.

**Comment by ericdill** [comment]
yes

**Comment by xhochy** [comment]
yes

**Comment by chenghlee** [comment]
yes

**Comment by cjmartian** [comment]
Yes

**Comment by msarahan** [comment]
yes

**Comment by mariusvniekerk** [comment]
yes

**Comment by goanpeca** [comment]
yes
