### ISSUE TITLE
Add conda recipe

### ISSUE THREAD

**Issue by dholth** [conda/conda-index#68]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

conda-index should have a conda recipe in recipe/meta.yaml

**Comment by AndresGuzman-Ballen** [comment]
Nice! :D

**Comment by AndresGuzman-Ballen** [comment]
Perhaps a dumb question but is uploading conda-index conda packages to the conda-forge channel on the horizon? No pressure; I imagine you have a large priority queue already :)

**Comment by dholth** [comment]
If you do it, add me to the recipe maintainers.

**Comment by jharlow-intel** [comment]
@dholth just letting you know a PR was created for the recipe and you were listed as a maintainer
https://github.com/conda-forge/staged-recipes/pull/21363

**Comment by AndresGuzman-Ballen** [comment]
Nice work @jharlow-intel !

**Comment by dholth** [comment]
Looks good. Has new conda index noticably sped up your work? No more # 3.9? comment needed, it's definitely available for python 3.7+ now.

**Comment by dholth** [comment]
Recipe exists.

**Comment by AndresGuzman-Ballen** [comment]
@dholth @jharlow-intel I see that there's now a conda package in conda-forge. Great work!

**Comment by dholth** [comment]
Thanks all!
