### ISSUE TITLE
Use same YAML library as conda?

### ISSUE THREAD

**Issue by dholth** [conda/conda-index#70]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

This requires PyYAML, it would be "prettier" to use the same one conda uses.

**Comment by jezdez** [comment]
Good idea!

**Comment by dholth** [comment]
ruamel.yaml provides all the same functions and exceptions, or we could import it from conda.serialization.
