### ISSUE TITLE
Provide a conda subcommand plugin

### ISSUE THREAD

**Issue by dholth** [conda/conda-index#81]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Conda has a new plugin system through which we can provide "conda index" (without using entry_points scripts). Provide one.

Will still need to figure out what to do about conda-build's "conda-index" script, which can also be called as "conda index".

Our command line arguments are necessarily different than legacy conda-index.

**Comment by barabo** [comment]
One possible use case would be to include the abilities to:
* re-index a specific package
* remove a package from the index
* add a specific package to the index

**Comment by dholth** [comment]
@barabo standalone conda-index is fast as long as stat'ing all the files is not a bottleneck (which it absolutely was for conda-forge on slow storage). It's designed so that you can subclass the part that does a listdir() and swap it out for a database query - listdir populates the database with a list of "currently available" files, then the index joins that list against the cached metadata for those files. It has to pull the index from its database, never from an existing repodata.json.

I haven't consulted the thesaurus to find a good replacement for the "index" name currently provided by conda-build, if we want to use the new, different click CLI.

**Comment by barabo** [comment]
If it would help, I can draft our more specific use cases / examples of what we would want a helper script / new functionality to do.
